# Generated by Django 2.2.12 on 2020-06-02 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EveCategory',
            fields=[
                ('id', models.PositiveIntegerField(help_text='Eve Online ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Eve Online name', max_length=100)),
                ('last_updated', models.DateTimeField(blank=True, db_index=True, default=None, help_text='When this object was last updated from ESI', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EveGroup',
            fields=[
                ('id', models.PositiveIntegerField(help_text='Eve Online ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Eve Online name', max_length=100)),
                ('last_updated', models.DateTimeField(blank=True, db_index=True, default=None, help_text='When this object was last updated from ESI', null=True)),
                ('eve_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveuniverse.EveCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EveType',
            fields=[
                ('id', models.PositiveIntegerField(help_text='Eve Online ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Eve Online name', max_length=100)),
                ('last_updated', models.DateTimeField(blank=True, db_index=True, default=None, help_text='When this object was last updated from ESI', null=True)),
                ('eve_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveuniverse.EveGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
