# Generated by Django 2.2.13 on 2020-06-22 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evedogmaeffectmodifier',
            name='modifying_effect',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='modifying_effects', to='eveuniverse.EveDogmaEffect'),
        ),
        migrations.AlterField(
            model_name='evedogmaeffectmodifier',
            name='modified_attribute',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='modified_attributes', to='eveuniverse.EveDogmaAttribute'),
        ),
        migrations.AlterField(
            model_name='evedogmaeffectmodifier',
            name='modifying_attribute',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='modifying_attributes', to='eveuniverse.EveDogmaAttribute'),
        ),
    ]
