# Generated by Django 2.2.13 on 2020-06-21 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evestargate',
            name='destination_eve_solar_system',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='destination_eve_solar_system_set', to='eveuniverse.EveSolarSystem'),
        ),
        migrations.AddField(
            model_name='evestargate',
            name='destination_eve_stargate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='destination_eve_stargate_set', to='eveuniverse.EveStargate'),
        ),
        migrations.DeleteModel(
            name='EveStargateDestination',
        ),
    ]
