# Generated by Django 2.2.13 on 2020-06-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0002_auto_20200622_0021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EveAncestries',
            new_name='EveAncestry',
        ),
    ]
