# Generated by Django 2.2.13 on 2020-06-06 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0002_auto_20200606_2045"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EveTypeDogmaAttributes", new_name="DogmaAttributes",
        ),
        migrations.RenameModel(
            old_name="EveTypeDogmaEffects", new_name="DogmaEffects",
        ),
    ]
