# Generated by Django 2.2.13 on 2020-06-07 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0003_auto_20200606_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveMarketGroup',
            fields=[
                ('id', models.PositiveIntegerField(help_text='Eve Online ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Eve Online name', max_length=100)),
                ('last_updated', models.DateTimeField(blank=True, db_index=True, default=None, help_text='When this object was last updated from ESI', null=True)),
                ('description', models.TextField()),
                ('parent_market_group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='eveuniverse.EveMarketGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
