# Generated by Django 2.2.13 on 2020-06-24 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0003_auto_20200624_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evestargate',
            name='destination_eve_solar_system',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='destination_eve_stargates', to='eveuniverse.EveSolarSystem'),
        ),
    ]
