# Generated by Django 2.2.13 on 2020-06-06 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0003_auto_20200603_2200"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveFaction",
            fields=[
                (
                    "id",
                    models.PositiveIntegerField(
                        help_text="Eve Online ID", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(help_text="Eve Online name", max_length=100)),
                (
                    "last_updated",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="When this object was last updated from ESI",
                        null=True,
                    ),
                ),
                (
                    "corporation_id",
                    models.PositiveIntegerField(default=None, null=True),
                ),
                ("description", models.TextField()),
                ("is_unique", models.BooleanField()),
                (
                    "militia_corporation_id",
                    models.PositiveIntegerField(default=None, null=True),
                ),
                ("size_factor", models.FloatField()),
                ("station_count", models.PositiveIntegerField()),
                ("station_system_count", models.PositiveIntegerField()),
                (
                    "eve_solar_system",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="eveuniverse.EveSolarSystem",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
