# Generated by Django 2.2.13 on 2020-06-25 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0004_auto_20200624_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evedogmaeffectmodifier',
            name='eve_dogma_effect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='eveuniverse.EveDogmaEffect'),
        ),
    ]
