# Generated by Django 2.2.13 on 2020-06-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0004_evemarketgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveDogmaAttribute',
            fields=[
                ('id', models.PositiveIntegerField(help_text='Eve Online ID', primary_key=True, serialize=False)),
                ('name', models.CharField(default='', help_text='Eve Online name', max_length=100)),
                ('last_updated', models.DateTimeField(blank=True, db_index=True, default=None, help_text='When this object was last updated from ESI', null=True)),
                ('default_value', models.FloatField(default=None, null=True)),
                ('description', models.TextField(default='')),
                ('display_name', models.CharField(default='', max_length=100)),
                ('high_is_good', models.BooleanField(default=None, null=True)),
                ('icon_id', models.PositiveIntegerField(db_index=True, default=None, null=True)),
                ('published', models.BooleanField(default=None, null=True)),
                ('stackable', models.BooleanField(default=None, null=True)),
                ('unit_id', models.PositiveIntegerField(default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='eveancestries',
            name='name',
            field=models.CharField(default='', help_text='Eve Online name', max_length=100),
        ),
        migrations.AlterField(
            model_name='eveasteroidbelt',
            name='name',
            field=models.CharField(default='', help_text='Eve Online name', max_length=100),
        ),
        migrations.AlterField(
            model_name='evebloodline',
            name='name',
            field=models.CharField(default='', help_text='Eve Online name', max_length=100),
        ),
        migrations.AlterField(
            model_name='evecategory',
            name='name',
            field=models.CharField(default='', help_text='Eve Online name', max_length=100),
        ),
        migrations.AlterField(
            model_name='eveconstellation',
            name='name',
            field=models.CharField(default='', help_text='Eve Online name', max_length=100),
        ),
        migrations.AlterField(
            model_name='evefaction',
            name='name',
            field=models.CharField(default='', help_text='Eve Online name', max_length=100),
        ),
        migrations.AlterField(
            model_name='evegroup',
            name='name',
            field=models.CharField(default='', help_text='Eve Online name', max_length=100),
        ),
        migrations.AlterField(
            model_name='evemarketgroup',
            name='name',
            field=models.CharField(default='', help_text='Eve Online name', max_length=100),
        ),
        migrations.AlterField(
            model_name='evemoon',
            name='name',
            field=models.CharField(default='', help_text='Eve Online name', max_length=100),
        ),
        migrations.AlterField(
            model_name='eveplanet',
            name='name',
            field=models.CharField(default='', help_text='Eve Online name', max_length=100),
        ),
        migrations.AlterField(
            model_name='everace',
            name='name',
            field=models.CharField(default='', help_text='Eve Online name', max_length=100),
        ),
        migrations.AlterField(
            model_name='everegion',
            name='name',
            field=models.CharField(default='', help_text='Eve Online name', max_length=100),
        ),
        migrations.AlterField(
            model_name='evesolarsystem',
            name='name',
            field=models.CharField(default='', help_text='Eve Online name', max_length=100),
        ),
        migrations.AlterField(
            model_name='evestar',
            name='name',
            field=models.CharField(default='', help_text='Eve Online name', max_length=100),
        ),
        migrations.AlterField(
            model_name='evestargate',
            name='name',
            field=models.CharField(default='', help_text='Eve Online name', max_length=100),
        ),
        migrations.AlterField(
            model_name='evestation',
            name='name',
            field=models.CharField(default='', help_text='Eve Online name', max_length=100),
        ),
        migrations.AlterField(
            model_name='evetype',
            name='name',
            field=models.CharField(default='', help_text='Eve Online name', max_length=100),
        ),
    ]
