# Generated by Django 2.2.13 on 2020-06-07 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0005_auto_20200607_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveDogmaEffect',
            fields=[
                ('id', models.PositiveIntegerField(help_text='Eve Online ID', primary_key=True, serialize=False)),
                ('name', models.CharField(default='', help_text='Eve Online name', max_length=100)),
                ('last_updated', models.DateTimeField(blank=True, db_index=True, default=None, help_text='When this object was last updated from ESI', null=True)),
                ('description', models.TextField(default='')),
                ('disallow_auto_repeat', models.BooleanField(default=None, null=True)),
                ('display_name', models.CharField(default='', max_length=100)),
                ('effect_category', models.PositiveIntegerField(default=None, null=True)),
                ('electronic_chance', models.BooleanField(default=None, null=True)),
                ('icon_id', models.PositiveIntegerField(db_index=True, default=None, null=True)),
                ('is_assistance', models.BooleanField(default=None, null=True)),
                ('is_offensive', models.BooleanField(default=None, null=True)),
                ('is_warp_safe', models.BooleanField(default=None, null=True)),
                ('post_expression', models.PositiveIntegerField(default=None, null=True)),
                ('pre_expression', models.PositiveIntegerField(default=None, null=True)),
                ('published', models.BooleanField(default=None, null=True)),
                ('range_chance', models.BooleanField(default=None, null=True)),
                ('discharge_attribute', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='discharge_attribute', to='eveuniverse.EveDogmaAttribute')),
                ('duration_attribute', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='eveuniverse.EveDogmaAttribute')),
                ('falloff_attribute', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='falloff_attribute', to='eveuniverse.EveDogmaAttribute')),
                ('range_attribute', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='range_attribute', to='eveuniverse.EveDogmaAttribute')),
                ('tracking_speed_attribute', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='tracking_speed_attribute', to='eveuniverse.EveDogmaAttribute')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EveDogmaEffectModifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(default='', max_length=100)),
                ('func', models.CharField(max_length=100)),
                ('operator', models.PositiveIntegerField(default=None, null=True)),
                ('eve_dogma_effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveuniverse.EveDogmaEffect')),
                ('modified_attribute', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='modified_attribute', to='eveuniverse.EveDogmaAttribute')),
                ('modifying_attribute', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='modifying_attribute', to='eveuniverse.EveDogmaAttribute')),
            ],
        ),
        migrations.CreateModel(
            name='EveTypeDogmaAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_id', models.PositiveIntegerField(db_index=True)),
                ('value', models.FloatField()),
                ('eve_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogma_attribute', to='eveuniverse.EveType')),
            ],
        ),
        migrations.CreateModel(
            name='EveTypeDogmaEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_id', models.PositiveIntegerField(db_index=True)),
                ('is_default', models.BooleanField()),
                ('eve_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogma_effect', to='eveuniverse.EveType')),
            ],
        ),
        migrations.RemoveField(
            model_name='dogmaeffects',
            name='eve_type',
        ),
        migrations.DeleteModel(
            name='DogmaAttributes',
        ),
        migrations.DeleteModel(
            name='DogmaEffects',
        ),
        migrations.AddConstraint(
            model_name='evetypedogmaeffect',
            constraint=models.UniqueConstraint(fields=('eve_type', 'effect_id'), name='functional PK'),
        ),
        migrations.AddConstraint(
            model_name='evetypedogmaattribute',
            constraint=models.UniqueConstraint(fields=('eve_type', 'attribute_id'), name='functional PK'),
        ),
        migrations.AddConstraint(
            model_name='evedogmaeffectmodifier',
            constraint=models.UniqueConstraint(fields=('eve_dogma_effect', 'func'), name='functional PK'),
        ),
    ]
