# Generated by Django 3.1.6 on 2021-02-23 15:50

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0005_evetypematerial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evetype",
            name="sections_loaded",
            field=bitfield.models.BitField(
                ("dogmas", "graphics", "market_groups", "type_materials"),
                default=None,
                help_text="Flags for loadable sections. True if instance was loaded with section.",
            ),
        ),
    ]
