# Generated by Django 2.2.13 on 2020-06-25 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0005_auto_20200625_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evedogmaeffect',
            name='discharge_attribute',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='discharge_attributes', to='eveuniverse.EveDogmaAttribute'),
        ),
        migrations.AlterField(
            model_name='evedogmaeffect',
            name='falloff_attribute',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='falloff_attributes', to='eveuniverse.EveDogmaAttribute'),
        ),
        migrations.AlterField(
            model_name='evedogmaeffect',
            name='range_attribute',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='range_attributes', to='eveuniverse.EveDogmaAttribute'),
        ),
        migrations.AlterField(
            model_name='evedogmaeffect',
            name='tracking_speed_attribute',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='tracking_speed_attributes', to='eveuniverse.EveDogmaAttribute'),
        ),
    ]
