# Generated by Django 2.2.13 on 2020-06-07 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0006_auto_20200607_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evetypedogmaattribute',
            name='eve_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogma_attributes', to='eveuniverse.EveType'),
        ),
        migrations.AlterField(
            model_name='evetypedogmaeffect',
            name='eve_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogma_effects', to='eveuniverse.EveType'),
        ),
    ]
