# Generated by Django 2.2.13 on 2020-06-25 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0006_auto_20200625_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveGraphic',
            fields=[
                ('id', models.PositiveIntegerField(help_text='Eve Online ID', primary_key=True, serialize=False)),
                ('name', models.CharField(default='', help_text='Eve Online name', max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, help_text='When this object was last updated from ESI')),
                ('collision_file', models.CharField(default='', max_length=255)),
                ('graphic_file', models.CharField(default='', max_length=255)),
                ('icon_folder', models.CharField(default='', max_length=255)),
                ('sof_dna', models.CharField(default='', max_length=255)),
                ('sof_fation_name', models.CharField(default='', max_length=255)),
                ('sof_hull_name', models.CharField(default='', max_length=255)),
                ('sof_race_name', models.CharField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='evetype',
            name='graphic_id',
        ),
        migrations.AddField(
            model_name='evetype',
            name='eve_graphic',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='eveuniverse.EveGraphic'),
        ),
    ]
