# Generated by Django 3.1.6 on 2021-02-24 16:01

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0007_auto_20210223_1620"),
    ]

    operations = [
        migrations.AddField(
            model_name="evesolarsystem",
            name="enabled_sections",
            field=bitfield.models.BitField(
                ("planets", "stargates", "stars", "stations"),
                default=None,
                help_text="Flags for loadable sections. True if instance was loaded with section.",
            ),
        ),
    ]
