# Generated by Django 3.1.6 on 2021-02-25 10:32

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0008_evesolarsystem_enabled_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="eveplanet",
            name="enabled_sections",
            field=bitfield.models.BitField(
                ("asteroid_belts", "moons"),
                default=None,
                help_text="Flags for loadable sections. True if instance was loaded with section.",
            ),
        ),
    ]
