# Generated by Django 2.2.13 on 2020-06-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0008_eveasteroidbelt"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveAncestries",
            fields=[
                (
                    "id",
                    models.PositiveIntegerField(
                        help_text="Eve Online ID", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(help_text="Eve Online name", max_length=100)),
                (
                    "last_updated",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="When this object was last updated from ESI",
                        null=True,
                    ),
                ),
                ("bloodline_id", models.PositiveIntegerField()),
                ("description", models.TextField()),
                ("icon_id", models.PositiveIntegerField(default=None, null=True)),
                ("short_description", models.TextField(default="")),
            ],
            options={"abstract": False,},
        ),
    ]
