# Generated by Django 2.2.13 on 2020-06-25 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0008_auto_20200625_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evedogmaeffect',
            name='discharge_attribute',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='discharge_attribute_effects', to='eveuniverse.EveDogmaAttribute'),
        ),
        migrations.AlterField(
            model_name='evedogmaeffect',
            name='duration_attribute',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='duration_attribute_effects', to='eveuniverse.EveDogmaAttribute'),
        ),
        migrations.AlterField(
            model_name='evedogmaeffect',
            name='falloff_attribute',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='falloff_attribute_effects', to='eveuniverse.EveDogmaAttribute'),
        ),
        migrations.AlterField(
            model_name='evedogmaeffect',
            name='range_attribute',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='range_attribute_effects', to='eveuniverse.EveDogmaAttribute'),
        ),
        migrations.AlterField(
            model_name='evedogmaeffect',
            name='tracking_speed_attribute',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='tracking_speed_attribute_effects', to='eveuniverse.EveDogmaAttribute'),
        ),
        migrations.AlterField(
            model_name='evedogmaeffectmodifier',
            name='modified_attribute',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='modified_attribute_modifiers', to='eveuniverse.EveDogmaAttribute'),
        ),
        migrations.AlterField(
            model_name='evedogmaeffectmodifier',
            name='modifying_attribute',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='modifying_attribute_modifiers', to='eveuniverse.EveDogmaAttribute'),
        ),
        migrations.AlterField(
            model_name='evedogmaeffectmodifier',
            name='modifying_effect',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='modifying_effect_modifiers', to='eveuniverse.EveDogmaEffect'),
        ),
        migrations.AlterField(
            model_name='evefaction',
            name='eve_solar_system',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='eve_factions', to='eveuniverse.EveSolarSystem'),
        ),
        migrations.AlterField(
            model_name='evemarketgroup',
            name='parent_market_group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='market_group_children', to='eveuniverse.EveMarketGroup'),
        ),
    ]
