# Generated by Django 2.2.13 on 2020-07-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0009_auto_20200625_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveEntity',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('category', models.CharField(choices=[('alliance', 'alliance'), ('character', 'character'), ('constellation', 'constellation'), ('corporation', 'corporation'), ('faction', 'faction'), ('inventory_type', 'inventory_type'), ('region', 'region'), ('solar_system', 'solar_system'), ('station', 'station')], default=None, max_length=16, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, help_text='When this object was last updated from ESI')),
            ],
        ),
    ]
