# Generated by Django 2.2.13 on 2020-06-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0010_evebloodlines"),
    ]

    operations = [
        migrations.RenameModel(old_name="EveBloodlines", new_name="EveBloodline",),
    ]
