# Generated by Django 2.2.13 on 2020-07-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0010_eveentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eveentity',
            name='id',
            field=models.PositiveIntegerField(help_text='Eve Online ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eveentity',
            name='name',
            field=models.CharField(default='', help_text='Eve Online name', max_length=100),
        ),
    ]
