# Generated by Django 2.2.13 on 2020-06-06 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0011_auto_20200606_1954"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evebloodline",
            name="eve_race",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="eveuniverse.EveRace",
            ),
        ),
    ]
